### get request
GET http://localhost:8000

### get task from server
GET   http://localhost:8000/api/v1/task

### Post task to server
POST  http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task":"watching TV",
    "hr":"12"
}

### Detele task to the serever
DELETE   http://localhost:8000/api/v1/task